### ISSUE TITLE
Missing operations

### ISSUE THREAD

**Issue by Kanaye** [LedgerHQ/app-stellar#12]
Hi, 
today I found that most newer operations are currently not implemented. 
Here the operations I found missing with their linked documentation

- [Path Payment Strict Send](https://developers.stellar.org/docs/start/list-of-operations/#path-payment-strict-send) | [**XDR**](https://github.com/stellar/stellar-core/blob/a0f109cc31ffb2009cbeb6a162f27daa82bd78b1/src/xdr/Stellar-transaction.x#L116-L129) (Path Payment Strict Receive seems to be implemented as `XDR_OPERATION_TYPE_PATH_PAYMENT ` )
- [Create Claimable Balance](https://developers.stellar.org/docs/start/list-of-operations/#create-claimable-balance) | [**XDR**](https://github.com/stellar/stellar-core/blob/a0f109cc31ffb2009cbeb6a162f27daa82bd78b1/src/xdr/Stellar-transaction.x#L306-L311)
- [Claim Claimable Balance](https://developers.stellar.org/docs/start/list-of-operations/#claim-claimable-balance) | [**XDR**](https://github.com/stellar/stellar-core/blob/a0f109cc31ffb2009cbeb6a162f27daa82bd78b1/src/xdr/Stellar-transaction.x#L306-L311)
- [Begin Sponsoring Future Reserves](https://developers.stellar.org/docs/start/list-of-operations/#begin-sponsoring-future-reserves) | [**XDR**](https://github.com/stellar/stellar-core/blob/a0f109cc31ffb2009cbeb6a162f27daa82bd78b1/src/xdr/Stellar-transaction.x#L333-L336)
- [End Sponsoring Future Reserves](https://developers.stellar.org/docs/start/list-of-operations/#end-sponsoring-future-reserves)
- [Revoke Sponsorship](https://developers.stellar.org/docs/start/list-of-operations/#revoke-sponsorship) | [**XDR**](https://github.com/stellar/stellar-core/blob/a0f109cc31ffb2009cbeb6a162f27daa82bd78b1/src/xdr/Stellar-transaction.x#L360-L377)

Unfortunatly you can't sign transactions containing one of these  operations and therefore not use apps relying on those.
For example [Stellar Quest](https://quest.stellar.org) tries to use the Operatioons `Begin Sponsoring Future Reserves` and `End Sponsoring Future Reserves` when claiming won prices.

While debugging this I also couldn't get hash-signing to work (always returns empty arrays) but had no chance to look into this yet.

**Comment by shadow87654** [comment]
These missing operations are causing issues with claiming Claimable Balances on the Stellar network. This needs fixing ASAP.
