### ISSUE TITLE
where is the ledgers for stellar ?

### ISSUE THREAD

**Issue by hench-ye** [LedgerHQ/app-stellar#24]
Hi, where is this website? thank you.
https://github.com/lenondupe/ledgerjs-stellar

**Comment by overcat** [comment]
If you are looking for Ledger Stellar JavaScript SDK, please check the following two links.
- https://github.com/LedgerHQ/ledgerjs
- https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-str
