### ISSUE TITLE
Solo ClaimClaimableBalanceOp signing fails with `Missing Critical Parameter`

### ISSUE THREAD

**Issue by paulbellamy** [LedgerHQ/app-stellar#30]
When trying to sign a transaction with a single ClaimClaimableBalance operation via the laboratory.stellar.org, I'm getting an error: `Error:"Ledger device: Missing critical parameter (0x6800)"`. When I add another operation into the transaction it signs fine (tried with a Payment, and a ChangeTrust).

This is on
OSX 11.4
Brave Browser Version 1.27.108 Chromium: 92.0.4515.107 (Official Build) (x86_64)
Ledger Nano X with latest Ledger Live.

XDR:
```
AAAAAgAAAAA3KuzYS5YlnZ7WiWh7dyxOTeAFLfsyJJcm2Sd613EspgAAAGQCNzYCAAAABAAAAAEAAAAAAAAAAAAAAABhNgPPAAAAAAAAAAEAAAAAAAAADwAAAAAiygg+iI3AQtdR6DCfHs4rCBV7DEptqyO1W2Rg7vOZxQAAAAAAAAAA
```

**Comment by overcat** [comment]
Hi @paulbellamy, this problem has been fixed in the master branch, please wait for @LedgerHQ to deploy a new version.

**Comment by otiitk** [comment]
Hello @overcat, when will the new version be deployed?

**Comment by overcat** [comment]
Hi @otiitk, the code is still waiting for security review by the Ledger team, so I can't provide an ETA now.

**Comment by paulbellamy** [comment]
No problem. I have a workaround, so no rush.

**Comment by overcat** [comment]
This issue has been fixed in the latest version.
