### ISSUE TITLE
A branch cannot be reached in the UX FLOW code

### ISSUE THREAD

**Issue by TamtamHero** [LedgerHQ/app-stellar#9]
(Imported from gitea, author: JB)

In display_next_screen (4f6e50024b/src/stellar_ux_nanox.c (L301-L303),) the last branch of a if / else if / else if / else statement cannot be reached

Compiler probably removes it, but in any case it could be deleted.

if(!hasDetails && !hasOperation){
	ux_flow_init(0, ux_confirm_tx_init_flow, NULL);
}
else if(hasOperation){
	ux_flow_init(0, ux_confirm_tx_operation_caption_flow, NULL);
}
else if(hasDetails){
	ux_flow_init(0, ux_confirm_tx_details_flow, NULL);
}
else{
	THROW(0x6111);
}

**Comment by overcat** [comment]
Hi @TamtamHero, it looks like this is an outdated issue, can we close it?
